export const blogList = [
    {
      id: 1,
      title: 'Males T-shirts, Jackets And Tops',
      category: 'males collections',
      subCategory: ['Male T-Shirts', 'male-Tops', 'Male Jackets'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'James Thomson',
      review: "They have what others don't have",
      authorAvatar: '/assets/images/com1.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/1.JPG',
    },
    {
      id: 2,
      title: 'Females Gean And Jackets ',
      category: 'females Selections',
      subCategory: ['Joggers', 'Female Denims', 'Geans'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Halton winfrey',
      review: "ReadyMade sells at best prices",
      authorAvatar: '/assets/images/com2.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/2.JPG',
    },
    {
      id: 3,
      title: 'Females Complete Suit Packages',
      category: 'Females Suit Only',
      subCategory: ['Suit Jackets', 'Female Blazers', 'Complete Suits'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Adebayo Olajide',
      review: "Quality is needed ReadyM got you",
      authorAvatar: '/assets/images/com3.png',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/3.JPG',
    },
    {
      id: 4,
      title: 'Italian Female Skirts, Shirts And Gowns',
      category: 'only females',
      subCategory: ['Female Skirts', 'Shirts', 'Gowns'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Elizabeth Vander puije',
      review: "Wears delivery are the fastest @RMF",
      authorAvatar: '/assets/images/com4.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/4.JPG',
    },
    {
      id: 5,
      title: 'Males Material And Geans Trousers',
      category: 'Trousers For Males',
      subCategory: ['Chinouse', 'Geans', 'Joggers'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'likang Kouh',
      review: "ReadyM have the future styles",
      authorAvatar: '/assets/images/com5.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/5.JPG',
    },
    {
      id: 6,
      title: 'Unisex Beach Wears',
      category: 'beach wears',
      subCategory: ['Male Shorts', 'Female Pants', 'Bucket Hat'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Annyson Kate',
      review: "ReadyMade offers uniquely",
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2021',
      cover:
        '/assets/images/6.JPG',
    },
    {
      id: 7,
      title: 'Traditional And Wedding Wears',
      category: 'traditional wears',
      subCategory: ['Aso-Oke', 'Fabric-Laces', 'Natives'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Benson Phillips',
      review: "ReadyMade offers uniquely",
      authorAvatar: '/assets/images/com7.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/7.JPG',
    },
    {
      id: 8,
      title: 'Unisex Winter Cardigans',
      category: 'winter wears',
      subCategory: ['Pull Overs', 'Full-Up Digans', 'Looner'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Lois Path Amber',
      review: "ReadyMade offers uniquely",
      authorAvatar: '/assets/images/com8.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/8.JPG',
    },
    {
      id: 9,
      title: 'Male Suit Collections ',
      category: 'suit collections',
      subCategory: ['Double Breast', 'singles', 'Goldens'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'John Doeker',
      review: "ReadyMade offers uniquely",
      authorAvatar: '/assets/images/com9.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/9.JPG',
    },
    {
      id: 10,
      title: 'Males T-shirts, Jackets And Tops',
      category: 'males collections',
      subCategory: ['Male T-Shirts', 'male-Tops', 'Male Jackets'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Cinthia Oliver',
      review: "They have what others don't have",
      authorAvatar: '/assets/images/com10.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/10.jpg',
    },
    {
      id: 11,
      title: 'Italian Female Skirts, Shirts And Gowns',
      category: 'only females',
      subCategory: ['Female Skirts', 'Shirts', 'Gowns'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Benson Phillips',
      review: "Wears delivery are the fastest @RMF",
      authorAvatar: '/assets/images/com7.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/11.jpg',
    },
    {
    id: 12,
      title: 'Unisex Beach Wears',
      category: 'beach wears',
      subCategory: ['Male Shorts', 'Female Pants', 'Bucket Hat'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Scott Williamson',
      review: "ReadyMade offers uniquely",
      authorAvatar: '/assets/images/com19.jpg',
      createdAt: 'June 03, 2021',
      cover:
        '/assets/images/12.jpg',
    },
    {
      id: 13,
      title: 'Unisex Winter Cardigans',
      category: 'winter wears',
      subCategory: ['Pull Overs', 'Full-Up Digans', 'Looner'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Charles Schurbid',
      review: "ReadyMade offers uniquely",
      authorAvatar: '/assets/images/com23.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/13.jpg',
    },
    {
      id: 14,
      title: 'Females Gean And Jackets ',
      category: 'Females Selections',
      subCategory: ['Joggers', 'Female Denims', 'Geans'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Jenifer Silver ',
      review: "ReadyMade sells at best prices",
      authorAvatar: '/assets/images/com13.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/14.jpg',
    },
    {
      id: 15,
      title: 'Traditional And Wedding Wears',
      category: 'traditional wears',
      subCategory: ['Aso-Oke', 'Fabric-Laces', 'Natives'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Pericy Magdalene',
      review: "ReadyMade offers uniquely",
      authorAvatar: '/assets/images/com21.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/7.JPG',
    },
    {
      id: 16,
      title: 'Male Suit Collections ',
      category: 'suit collections',
      subCategory: ['Double Breast', 'singles', 'Goldens'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Design Tek Experts Group',
      review: "ReadyMade offers uniquely",
      authorAvatar: '/assets/images/com25.png',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/16.jpg',
    },
    {
      id: 17,
      title: 'Females Complete Suit Packages',
      category: 'Females Suit Only',
      subCategory: ['Suit Jackets', 'Female Blazers', 'Complete Suits'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Soulz B. Esther',
      review: "Quality is needed ReadyM got you",
      authorAvatar: '/assets/images/com14.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/17.jpg',
    },
    {
      id: 18,
      title: 'Males Material And Geans Trousers',
      category: 'Trousers For Males',
      subCategory: ['Chinouse', 'Geans', 'Joggers'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Stephen O. Gerrald',
      review: "ReadyM have the future styles",
      authorAvatar: '/assets/images/com17.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/18.jpg',
    },
    {
      id: 19,
      title: 'Italian Female Skirts, Shirts And Gowns',
      category: 'only females',
      subCategory: ['Female Skirts', 'Shirts', 'Gowns'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Elizabeth Vander puije',
      review: "Wears delivery are the fastest @RMF",
      authorAvatar: '/assets/images/com16.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/19.jpg',
    },
    {
      id: 20,
      title: 'Unisex Winter Cardigans',
      category: 'winter wears',
      subCategory: ['Pull Overs', 'Full-Up Digans', 'Looner'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Rosemary Tinthy',
      review: "ReadyMade offers uniquely",
      authorAvatar: '/assets/images/com24.jpg',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/20.jpg',
    },
    {
      id: 21,
      title: 'Males T-shirts, Jackets And Tops',
      category: 'males collections',
      subCategory: ['Male T-Shirts', 'male-Tops', 'Male Jackets'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Andrew Peters',
      review: "They have what others don't have",
      authorAvatar: '/assets/images/com11.png',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/21.jpg',
    },
    {
      id: 22,
      title: 'Unisex Beach Wears',
      category: 'beach wears',
      subCategory: ['Male Shorts', 'Female Pants', 'Bucket Hat'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Roithek Huhg',
      review: "ReadyMade offers uniquely",
      authorAvatar: '/assets/images/com20.jpg',
      createdAt: 'June 03, 2021',
      cover:
        '/assets/images/22.jpg',
    },
    {
      id: 23,
      title: 'Traditional And Wedding Wears',
      category: 'traditional wears',
      subCategory: ['Aso-Oke', 'Fabric-Laces', 'Natives'],
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
      authorName: 'Ebuka Ucheze',
      review: "ReadyMade offers uniquely",
      authorAvatar: '/assets/images/com22.png',
      createdAt: 'June 03, 2021',
      cover: '/assets/images/23.jpg',
    },
  {
    id: 24,
    title: 'Females Gean And Jackets ',
    category: 'Females Selections',
    subCategory: ['Joggers', 'Female Denims', 'Geans'],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'John Doeker',
    review: "ReadyMade sells at best prices",
    authorAvatar: '/assets/images/com9.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/24.jpg',
  },
  {
    id: 25,
    title: 'Females Complete Suit Packages',
    category: 'Females Suit Only',
    subCategory: ['Suit Jackets', 'Female Blazers', 'Complete Suits'],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Adeoye Olajumoke',
    review: "Quality is needed ReadyM got you",
    authorAvatar: '/assets/images/com15.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/25.png',
  },
  {
    id: 26,
    title: 'Male Suit Collections ',
    category: 'suit collections',
    subCategory: ['Double Breast', 'singles', 'Goldens'],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Earlin Nightingale',
    review: "ReadyMade offers uniquely",
    authorAvatar: '/assets/images/com26.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/26.jpg',
  },
  {
    id: 27,
    title: 'Males Material And Geans Trousers',
    category: 'Trousers For Males',
    subCategory: ['Chinouse', 'Geans', 'Joggers'],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Glimestone Pearl',
    review: "ReadyM have the future styles",
    authorAvatar: '/assets/images/com18.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/27.jpg',
  },
  ];